server:
  port: 8082

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products-online-store
    username: worker
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect